development:
  adapter: mysql
  database: my_app_dev
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: my_app_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: my_app_production
  pool: 5
  timeout: 5000