# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: overbury_dev
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: overbury_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: overbury_production
  pool: 5
  timeout: 5000
