development: &non_production_settings
  site_name: Carbon Calculator (development)
  site_host: localhost:3000
  noreply_email: noreply@ineedadomainname.com

test:
  <<: *non_production_settings
  site_name: Carbon Calculator (test)

staging:
  <<: *non_production_settings  
  site_name: Carbon Calculator (staging)

production:
  <<: *non_production_settings  
  site_name: Carbon Calculator